services :
  simple-apps:
    container_name: ct-simpleapps
    image: fatoni07/img-simpleapps:v1-stable
    build: ./app
    ports:
      - "10000:3000"
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 128M