services :
  simple-apps:
    container_name: ct-simpleapps-prod-pipeline1
    build: ./app
    image: fatoni07/img-simpleapps:v1-stable
    ports:
      - "100002:3000"
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 128M